codecov:
  require_ci_to_pass: no

github_checks:
  annotations: false

coverage:
  precision: 2
  round: down
  range: "0...100"
  status:
    project:
      default: false
    patch:
      default:
        if_not_found: success
        informational: true
        only_pulls: false
        flags:
          - fxa-auth-server
          - many

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: false

flags:
  fxa-auth-server:
    paths:
      - packages/fxa-auth-server
    carryforward: true
  many:
    paths:
      - packages/fxa-admin-panel
      - packages/fxa-customs-server
      - packages/fxa-payments-server
      - packages/fxa-profile-server
      - packages/fxa-shared
    carryforward: true
