codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "0...100"
  status:
    project:
      default: false
    patch:
      default:
        if_not_found: success
        informational: true
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: false
