nodeLinker: node-modules

packageExtensions:
  "@apollo/react-common@*":
    dependencies:
      "@types/react": 16.9.35
      apollo-client: 2.6.10
      apollo-utilities: 1.3.4
      graphql: 14.6.0
  "@apollo/react-components@*":
    dependencies:
      apollo-cache: 1.3.5
      apollo-client: 2.6.10
      apollo-link: 1.2.14
      apollo-utilities: 1.3.4
  "@apollo/react-ssr@*":
    dependencies:
      "@types/react": 16.9.35
      apollo-client: 2.6.10
      graphql: 14.6.0
  "@storybook/addon-actions@*":
    dependencies:
      react-dom: 16.13.1
      regenerator-runtime: 0.13.5
  "@storybook/addon-links@*":
    dependencies:
      react-dom: 16.13.1
      regenerator-runtime: 0.13.5
  "@storybook/addons@*":
    dependencies:
      regenerator-runtime: 0.13.5
  "@storybook/api@*":
    dependencies:
      react-dom: 16.13.1
  apollo-link-error@*:
    dependencies:
      graphql: 14.6.0
  fxa-notifier-aws@*:
    dependencies:
      aws-sdk: ^2.698.0
  fxa-pairing-channel@*:
    dependencies:
      webpack: 4.43.0
  intern@*:
    dependencies:
      typescript: 3.9.7
  react-document-title@*:
    dependencies:
      react: 16.13.1
  webpack@*:
    dependencies:
      watchpack: 1.7.2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.1.1.cjs
