nodeLinker: node-modules

packageExtensions:
  fxa-pairing-channel@*:
    dependencies:
      webpack: ^4.43.0
  react-document-title@*:
    dependencies:
      react: ^16.13.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-relock.js
    spec: "@yarnpkg/plugin-relock"
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://github.com/mskelton/yarn-plugin-outdated/raw/main/bundles/@yarnpkg/plugin-outdated.js"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
