about:
  description: Nimbus Feature Manifest for FxA Frontend Experimentation
channels:
  - development
  - stage
  - release
features:
  example-feature:
    description: An example feature
    variables:
      enabled:
        description: If the feature is enabled
        type: Boolean
        default: false
      something:
        description: Another variable
        type: Option<String>
        default: null
    defaults:
      - channel: development
        value: { "enabled": false }
      - channel: stage
        value: { "enabled": true }
      - channel: release
        value: { "something": "nice" }

types:
  objects: {}
  enums: {}
