/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/**
 * Challenge lifecycle types for passkey (WebAuthn) ceremonies.
 *
 * Challenges are ephemeral, single-use values stored in Redis with TTL-based expiration.
 * They secure the registration and authentication ceremonies against replay attacks.
 *
 * Redis key format: `passkey:challenge:{type}:{challengeBase64url}`
 *
 * @see libs/accounts/passkey/CHALLENGE_DESIGN.md for the full architectural design.
 */

/**
 * Discriminates between the three WebAuthn ceremony types.
 *
 * - 'registration': Attestation ceremony — adding a new passkey to an existing, verified
 *   account (MFA-gated; uid is always available).
 *
 * - 'authentication': Assertion ceremony — discoverable credential sign-in. The server has
 *   NO uid when generating the challenge because `authenticationStart` is unauthenticated.
 *   The uid is only known after `authenticationVerify` resolves the credential ID.
 *
 * - 'upgrade': Assertion ceremony — PRF key-wrapping flow (`upgradeStart`/`upgradeVerify`).
 *   Typed separately from 'authentication' to prevent cross-ceremony attacks where an
 *   upgrade challenge could not be submitted to the sign-in verification endpoint and
 *   vice versa. Requires MFA JWT; uid is always available.
 */
export type ChallengeType = 'registration' | 'authentication' | 'upgrade';

/**
 * Redis key prefix for all passkey challenge records.
 * Full key format: `{PASSKEY_CHALLENGE_REDIS_PREFIX}:{type}:{challengeBase64url}`
 */
export const PASSKEY_CHALLENGE_REDIS_PREFIX = 'passkey:challenge';

/**
 * The shape of a challenge record stored as a JSON value in Redis.
 *
 * Design notes:
 * - `uid` is a hex string (not a Buffer) for clean JSON serialization, consistent
 *   with recovery-phone.manager.ts.
 * - `uid` is optional: authentication (sign-in) challenges are generated before the user
 *   is identified. Registration and upgrade challenges always include uid (both are
 *   MFA-gated and require an authenticated session).
 * - `expiresAt` is informational; the Redis TTL (`EX` on SET) is the authoritative expiry
 *   mechanism. The application may compare `expiresAt` against `Date.now()` if it receives
 *   a challenge that Redis has not yet evicted.
 * - The `challenge` field (base64url-encoded 32 random bytes) is also the Redis key suffix,
 *   enabling direct lookup from the challenge bytes returned by the WebAuthn ceremony.
 */
export interface StoredChallenge {
  /**
   * Base64url-encoded 32 random bytes generated by crypto.randomBytes(32).
   * This value is:
   * 1. Included in the WebAuthn options returned to the client.
   * 2. Signed by the authenticator and embedded in clientDataJSON.
   * 3. Used as the Redis key suffix for lookup during verification.
   */
  challenge: string;

  /** The WebAuthn ceremony type. Validated during consumption. */
  type: ChallengeType;

  /**
   * Hex-encoded user ID (16 bytes = 32 hex chars).
   *
   * Present for 'registration' and 'upgrade' challenges (both MFA-gated; uid is known).
   * Absent for 'authentication' challenges: sign-in uses discoverable credentials and
   * authenticationStart is unauthenticated — the uid is only resolved after the ceremony.
   */
  uid?: string;

  /** Unix timestamp (milliseconds) when this challenge was created. */
  createdAt: number;

  /**
   * Unix timestamp (milliseconds) when this challenge expires.
   * Derived from `PasskeyConfig.challengeTimeout` (default: 300,000 ms / 5 minutes).
   * Informational only — Redis TTL is the enforcement mechanism.
   */
  expiresAt: number;
}

/**
 * Input for generating a registration challenge.
 * Requires an authenticated session with MFA JWT — uid is always known.
 */
export interface CreateRegistrationChallengeInput {
  uid: string;
}

/**
 * Input for generating an authentication (sign-in) challenge.
 *
 * uid is NOT provided: `authenticationStart` is unauthenticated and uses discoverable
 * credentials. The authenticator identifies the user — the server only learns the uid
 * after the ceremony response is verified in `authenticationVerify`.
 */
export type CreateAuthenticationChallengeInput = Record<never, never>;

/**
 * Input for generating an upgrade challenge (PRF key-wrapping ceremony).
 * Requires an authenticated session with MFA JWT — uid is always known.
 */
export interface CreateUpgradeChallengeInput {
  uid: string;
}
