/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

define([
  './functional/sign_in',
  './functional/sign_in_cached',
  './functional/sync_sign_in',
  './functional/sync_force_auth',
  './functional/sign_up',
  './functional/complete_sign_up',
  './functional/sync_sign_up',
  './functional/sync_v2_sign_up',
  './functional/firstrun_sign_up',
  './functional/firstrun_sign_in',
  './functional/fx_ios_v1_sign_in',
  './functional/fx_ios_v1_sign_up',
  './functional/fx_ios_v2_sign_up',
  './functional/fx_fennec_v1_sign_in',
  './functional/fx_fennec_v1_force_auth',
  './functional/fx_fennec_v1_sign_up',
  './functional/verification_experiments',
  './functional/bounced_email',
  './functional/legal',
  './functional/tos',
  './functional/pp',
  './functional/confirm',
  './functional/delete_account',
  './functional/reset_password',
  './functional/sync_reset_password',
  './functional/robots_txt',
  './functional/settings',
  './functional/settings_common',
  './functional/sync_settings',
  './functional/change_password',
  './functional/force_auth',
  './functional/404',
  './functional/500',
  './functional/pages',
  './functional/back_button_after_start',
  './functional/cookies_disabled',
  './functional/fonts',
  './functional/password_visibility',
  './functional/avatar',
  './functional/alternative_styles',
  './functional/email_opt_in',
  './functional/refreshes_metrics',
], function () {});
