/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

module.exports = [
  'tests/server/routes.js',
  'tests/server/l10n-entrained.js',
  'tests/server/ver.json.js',
  'tests/server/amplitude.js',
  'tests/server/csp.js',
  'tests/server/flow-event.js',
  'tests/server/flow-metrics.js',
  'tests/server/html-middleware.js',
  'tests/server/l10n.js',
  'tests/server/lang.js',
  'tests/server/metrics.js',
  'tests/server/metrics-collector-stderr.js',
  'tests/server/metrics-errors.js',
  'tests/server/metrics-unit.js',
  'tests/server/noindex.js',
  'tests/server/configuration.js',
  'tests/server/raven.js',
  'tests/server/routes/get-apple-app-site-association.js',
  'tests/server/routes/get-config.js',
  'tests/server/routes/get-frontend-pairing.js',
  'tests/server/routes/get-fxa-client-configuration.js',
  'tests/server/routes/get-index.js',
  'tests/server/routes/get-lbheartbeat.js',
  'tests/server/routes/get-metrics-flow.js',
  'tests/server/routes/get-oauth-success.js',
  'tests/server/routes/get-openid-configuration.js',
  'tests/server/routes/get-update-firefox.js',
  'tests/server/routes/get-well-known-change-password.js',
  'tests/server/routes/post-csp.js',
  'tests/server/routes/post-metrics.js',
  'tests/server/routes/redirect-download-firefox.js',
  'tests/server/routes/redirect-m-to-adjust.js',
  'tests/server/routes/validate-email-domain.js',
  'tests/server/logging/route_logging.js',
  'tests/server/validation.js',
];
