/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// AUTOGENERATED BY glean_parser v14.1.2. DO NOT EDIT. DO NOT COMMIT.

import EventMetricType from '@mozilla/glean/private/metrics/event';

/**
 * User sees Apple link and bypasses Mozilla Accounts email first/login
 * screens (relevant for Pocket)
 *
 * Generated from `third_party_auth.apple_deeplink`.
 */
export const appleDeeplink = new EventMetricType(
  {
    category: 'third_party_auth',
    name: 'apple_deeplink',
    sendInPings: ['events'],
    lifetime: 'ping',
    disabled: false,
  },
  []
);

/**
 * User sees Google link and bypasses Mozilla Accounts email first/login
 * screens (relevant for Pocket)
 *
 * Generated from `third_party_auth.google_deeplink`.
 */
export const googleDeeplink = new EventMetricType(
  {
    category: 'third_party_auth',
    name: 'google_deeplink',
    sendInPings: ['events'],
    lifetime: 'ping',
    disabled: false,
  },
  []
);
