'use strict';

const PASSWORD_BALLOON = {
  BALLOON: '#password-strength-balloon',
  MIN_LENGTH_FAIL: '#password-too-short.password-strength-fail',
  MIN_LENGTH_MET: '#password-too-short.password-strength-unmet',
  MIN_LENGTH_UNMET: '#password-too-short.password-strength-unmet',
  NOT_COMMON_FAIL: '#password-too-common.password-strength-fail',
  NOT_COMMON_MET: '#password-too-common.password-strength-unmet',
  NOT_COMMON_UNMET: '#password-too-common.password-strength-unmet',
  NOT_EMAIL_FAIL: '#password-same-as-email.password-strength-fail',
  NOT_EMAIL_MET: '#password-same-as-email.password-strength-unmet',
  NOT_EMAIL_UNMET: '#password-same-as-email.password-strength-unmet',
};

/*eslint-disable max-len*/
module.exports = {
  CONFIRM_SIGNIN: {
    HEADER: '#fxa-confirm-signin-header',
    LINK_BACK: '#back',
    LINK_RESEND: '#resend',
    RESEND_SUCCESS: '.success',
  },
  CONFIRM_SIGNUP: {
    EMAIL_MESSAGE: '.verification-email-message',
    HEADER: '#fxa-confirm-header',
    LINK_BACK: '#back',
    LINK_OPEN_WEBMAIL: '#open-webmail',
    LINK_RESEND: '#resend',
  },
  CONFIRM_SIGNUP_CODE: {
    HEADER: '#fxa-confirm-signup-code-header',
    SUB_HEADER: '#subheader',
    EMAIL_FIELD: '#verification-email-message',
    INPUT: '#otp-code',
    LINKS: '#links',
    LINK_BACK: '#back',
    LINK_RESEND: '#resend',
  },
  ENTER_EMAIL: {
    EMAIL: 'input[type=email]',
    ERROR: '.error',
    SYNC_DESCRIPTION: '#subheader',
    FIREFOX_FAMILY_SERVICES: '#firefox-family-services',
    HEADER: '#fxa-enter-email-header',
    LINK_SUGGEST_EMAIL_DOMAIN_CORRECTION: '#email-suggestion',
    LINK_SUGGEST_SYNC: '#suggest-sync a',
    SUB_HEADER: '#subheader',
    SUBMIT: 'button[type="submit"]',
    SUGGEST_EMAIL_DOMAIN_CORRECTION: '.tooltip-suggest',
    TOOLTIP: 'input[type=email] ~ .tooltip',
    TOOLTIP_BOUNCED_EMAIL: 'input[type=email] ~ .tooltip',
  },
  FORCE_AUTH: {
    EMAIL: 'input[type=email]',
    EMAIL_NOT_EDITABLE: '#prefillEmail',
    HEADER: '#fxa-force-auth-header',
    LINK_RESET_PASSWORD: '#reset-password',
    PASSWORD: 'input[type=password]',
    SUB_HEADER: '#subheader',
    SUB_HEADER_SYNC: '#subheader',
  },
  RESET_PASSWORD_COMPLETE: {
    HEADER: '#fxa-reset-password-complete-header',
    SUB_HEADER: '.account-ready-service',
  },
  SIGNIN_COMPLETE: {
    CONTINUE_BUTTON: '.btn-continue',
    HEADER: '#fxa-sign-in-complete-header',
    SERVICE_NAME: '.account-ready-service',
  },
  SIGNIN_PASSWORD: {
    EMAIL: 'input[type=email]',
    EMAIL_NOT_EDITABLE: '#prefillEmail',
    ERROR: '.error',
    HEADER: '#fxa-signin-password-header',
    LINK_FORGOT_PASSWORD: 'a[href^="/reset_password"]',
    LINK_USE_DIFFERENT: '#use-different',
    PASSWORD: 'input[type=password]',
    SHOW_PASSWORD: '#password ~ [for^="show-"]',
    SUB_HEADER: '#subheader',
    SUB_HEADER_ENTER_PW: '#subheader',
    SUCCESS: '.success',
    SUBMIT: 'button[type="submit"]',
    SUBMIT_USE_SIGNED_IN: '#use-logged-in',
    TOOLTIP: 'input[type=password] ~ .tooltip',
  },
  SIGNIN_TOKEN_CODE: {
    EMAIL_FIELD: '#verification-email-message',
    ERROR: '.error',
    HEADER: '#fxa-signin-code-header',
    INPUT: '#otp-code',
    LINK_RESEND: '#resend',
    SUCCESS: '.success',
    SUBMIT: 'button[type="submit"]',
    TOOLTIP: '.tooltip',
  },
  SIGNUP_COMPLETE: {
    CONTINUE_BUTTON: '.btn-continue',
    HEADER: '#fxa-sign-up-complete-header',
    SERVICE_NAME: '.account-ready-service',
  },
  SIGNUP_PASSWORD: {
    AGE: '#age',
    CHOOSE_WHAT_TO_SYNC_HEADER: '#fxa-choose-what-to-sync-header',
    COPPA_LINK: '#coppa-link',
    EMAIL: 'input[type=email]',
    ERROR: '.error',
    ERROR_PASSWORDS_DO_NOT_MATCH: '.error',
    HEADER: '#fxa-signup-password-header',
    LINK_USE_DIFFERENT: '#use-different',
    MARKETING_EMAIL_OPTIN: 'input.input-checkbox',
    PASSWORD: '#password',
    PASSWORD_BALLOON,
    PRIVACY_POLICY: '#fxa-pp',
    SHOW_PASSWORD: '#password ~ [for="show-password"]',
    SHOW_VPASSWORD: '#vpassword ~ [for="show-vpassword"]',
    SUBMIT: 'button[type="submit"]',
    TOOLTIP_AGE_REQUIRED: '#age ~ .tooltip',
    TOS: '#fxa-tos',
    TOOLTIP: '.tooltip',
    VPASSWORD: '#vpassword',
  },
  THIRD_PARTY_AUTH: {
    GOOGLE: '#google-login-button',
    APPLE: '#apple-login-button',
  },
};
/*eslint-enable max-len*/