version: '2.1'
services:
  fxa-oauth-console:
    build:
      context: .
      dockerfile: Dockerfile-build
    command: node bin/server.js
    image: mozilla/fxa-oauth-console
    ports:
      - '10137:10137'
    environment:
      PROFILE_URI: http://127.0.0.1:1111/profile/v1
      OAUTH_URI: http://127.0.0.1:9010/v1
      OAUTH_INTERNAL_URI: http://127.0.0.1:9011/v1
