## Backend failure based errors
auth-error-998 = System unavailable, try again soon
auth-error-999 = Unexpected error

## Auth-server based errors that originate from backend service
auth-error-101 = Account already exists
auth-error-102 = Unknown account
auth-error-120 = Incorrect email case
auth-error-103 = Incorrect password
auth-error-104 = Unverified account
auth-error-105 = Invalid verification code
auth-error-106 = Invalid JSON in request body
auth-error-109 = Invalid request signature
auth-error-110 = Invalid token
auth-error-111 = Invalid timestamp in request signature
auth-error-112 = Missing content-length header
auth-error-113 = Request body too large
auth-error-114 = You've tried too many times. Try again later.
auth-error-115 = Invalid nonce in request signature
auth-error-125 = The request was blocked for security reasons
auth-error-126 = Your account has been locked for security reasons
auth-error-127 = Invalid authorization code
auth-error-129 = Invalid phone number
auth-error-130 = Cannot send to this country
auth-error-131 = SMS ID invalid
auth-error-132 = Could not send a message to this number
auth-error-133 = Your email was just returned
auth-error-134 = Your email was just returned. Mistyped email?
auth-error-135 = Unable to deliver email
auth-error-136 = This email was already verified by another user
auth-error-138 = Unverified session
auth-error-139 = Secondary email must be different than your account email
auth-error-140 = Account already exists
auth-error-141 = Account already exists
auth-error-142 = Primary account email required for sign-in
auth-error-144 = Address in use by another account
auth-error-145 = Primary account email required for reset
auth-error-146 = Invalid signin code
auth-error-147 = Can not change primary email to an unverified email
auth-error-148 = Can not change primary email to an email that does not belong to this account
auth-error-149 = This email can not currently be used to login
auth-error-150 = Can not change primary email to an email that does not belong to this account
auth-error-151 = Failed to send email
auth-error-152 = Valid code required
auth-error-153 = This verification code has expired
auth-error-154 = A TOTP token already exists for this account
auth-error-155 = TOTP token not found
auth-error-156 = Recovery code not found
auth-error-157 = Unavailable device command
auth-error-158 = Recovery key not found
auth-error-159 = Invalid recovery key
auth-error-160 = This request requires two step authentication enabled on your account.
auth-error-165 = Failed due to a conflicting request, please try again.
auth-error-170 = This request requires two step authentication enabled on your account.
auth-error-176 = Unknown customer for subscription.
auth-error-177 = Unknown subscription.
auth-error-178 = Unknown plan for subscription.
auth-error-179 = Invalid payment token for subscription.
auth-error-180 = Subscription has already been cancelled
auth-error-181 = Update was rejected, please try again
auth-error-183 = Invalid or expired verification code
auth-error-188 = You have reached the maximum allowed secondary emails
auth-error-189 = This email already exists on your account
auth-error-190 = Could not update Ecosystem Anon ID because precondition failed.
auth-error-201 = Server busy, try again soon
auth-error-202 = Feature not enabled
auth-error-203 = System unavailable, try again soon
auth-error-204 = System unavailable, try again soon
auth-error-116 = This endpoint is no longer supported

# Auth based errors surfaced to users, ie through settings UI
auth-error-1001 = Login attempt cancelled
auth-error-1002 = Session expired. Sign in to continue.
auth-error-1003 = Cookies are still disabled
auth-error-1004 = Passwords do not match
auth-error-1005 = Working…
auth-error-1006 = Could not get Privacy Notice
auth-error-1007 = Could not get Terms of Service
auth-error-1008 = Your new password must be different
auth-error-1009 = Must be at least 8 characters
auth-error-1010 = Valid password required
auth-error-1011 = Valid email required
auth-error-1013 = A usable image was not found
auth-error-1014 = Could not initialize camera
auth-error-1015 = Valid URL required
auth-error-1017 = Unexpected error
auth-error-1018 = Your verification email was just returned. Mistyped email?
auth-error-1019 = Valid email required
auth-error-1020 = Enter a valid email address. firefox.com does not offer email.
auth-error-1021 = Unexpected error
auth-error-1022 = Firefox Accounts can only be placed into an IFRAME on approved sites
auth-error-1023 = Valid email required
auth-error-1025 = The link you clicked to verify your email is expired.
auth-error-1026 = Verification link damaged
auth-error-1027 = Unexpected error
auth-error-1028 = The image dimensions must be at least 100x100px
auth-error-1029 = Signup is coming soon to Firefox for iOS
auth-error-1031 = You must enter your age to sign up
auth-error-1032 = You must enter a valid age to sign up
auth-error-1033 = Unexpected error
auth-error-1034 = Account no longer exists.
auth-error-1039 = Server busy, try again soon
auth-error-1040 = The link you clicked to verify your email is expired.
auth-error-1041 = That confirmation link was already used, and can only be used once.
auth-error-1042 = This is a required field
auth-error-1043 = Authorization code required
auth-error-1044 = Invalid authorization code
auth-error-1045 = Link damaged
auth-error-1050 = Account has no uid
auth-error-1051 = Browser not configured to accept WebChannel messages from this domain
auth-error-1052 = That confirmation link was already used, and can only be used once.
auth-error-1053 = Two-step authentication code required
auth-error-1054 = Invalid two-step authentication code
auth-error-1055 = Recovery code required
auth-error-1056 = Invalid recovery code
auth-error-1057 = Password must not be your email address
auth-error-1058 = Password is too common
auth-error-1059 = Recovery key required
auth-error-1060 = Please enter verification code
auth-error-1062 = Invalid redirect
auth-error-1065 = The image file size is too large to be uploaded.

