---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fxa-content-server
  description: Front-end for Mozilla Accounts
  tags:
    - javascript
    - typescript
    - node
    - backbone
    - react
  annotations:
    sentry.io/project-slug: mozilla/fxa-content-server
    circleci.com/project-slug: github/mozilla/fxa
  links:
    - url: https://accounts.firefox.com/
      title: Production Mozilla Accounts
      type: website
    - url: https://accounts.stage.mozaws.net/
      title: Stage Mozilla Accounts
      type: website
spec:
  type: website
  lifecycle: production
  owner: fxa-team
  system: mozilla-accounts
  dependsOn:
    - component:fxa-auth-server
