import { ApolloWrapper } from '@fxa/payments-ui';
import './global.css';

export const metadata = {
  title: 'Welcome to payments-next',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
