/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// AUTOGENERATED BY glean_parser v19.2.0. DO NOT EDIT. DO NOT COMMIT.

import EventMetricType from '@mozilla/glean/private/metrics/event';

/**
 * Pairing completed end-to-end. Fires on the desktop (authority) when the
 * "Device connected" success screen is displayed, which only happens after the
 * desktop has approved the pairing AND the mobile device (supplicant) has
 * confirmed it. Distinct from `cad_approve_device.submit` and
 * `cad_mobile_pair.submit`, which are per-side intents that do not guarantee
 * the pairing succeeded.
 *
 * Generated from `cad_pair.success`.
 */
export const success = new EventMetricType(
  {
    category: 'cad_pair',
    name: 'success',
    sendInPings: ['events'],
    lifetime: 'ping',
    disabled: false,
  },
  []
);
