-- SET NAMES utf8mb4 COLLATE utf8mb4_bin;
--
-- DELETE FROM securityEventNames WHERE name = 'account.recovery_phone_reset_password_complete';
-- DELETE FROM securityEventNames WHERE name = 'account.recovery_phone_reset_password_failed';
--
-- UPDATE dbMetadata SET value = '168' WHERE name = 'schema-patch-level';
