-- SET NAMES utf8mb4 COLLATE utf8mb4_bin;
-- 
-- DROP PROCEDURE createAccountSubscription_1;
-- DROP PROCEDURE deleteAccountSubscription_1;
-- DROP PROCEDURE getAccountSubscription_1;
-- DROP PROCEDURE fetchAccountSubscriptions_1;
-- DROP PROCEDURE deleteAccount_17;
-- 
-- DROP TABLE accountSubscriptions;
-- 
-- UPDATE dbMetadata SET value = '97' WHERE name = 'schema-patch-level';
