-- SET NAMES utf8mb4 COLLATE utf8mb4_bin;
--
-- DELETE FROM emailTypes WHERE emailType IN (
--   'cadReminderFirst',
--   'cadReminderSecond',
--   'fraudulentAccountDeletion',
--   'inactiveAccountFinalWarning',
--   'inactiveAccountFirstWarning',
--   'inactiveAccountSecondWarning',
--   'passwordForgotOtp',
--   'passwordResetWithRecoveryKeyPrompt',
--   'postAddLinkedAccount',
--   'postAddRecoveryPhone',
--   'postChangeAccountRecovery',
--   'postChangeRecoveryPhone',
--   'postRemoveRecoveryPhone',
--   'postSigninRecoveryCode',
--   'postSigninRecoveryPhone',
--   'subscriptionAccountReminderFirst',
--   'subscriptionAccountReminderSecond',
--   'verificationReminderFinal',
--   'verificationReminderFirst',
--   'verificationReminderSecond'
-- );
--
-- UPDATE dbMetadata SET value = '160' WHERE name = 'schema-patch-level';
