-- SET NAMES utf8mb4 COLLATE utf8mb4_bin;
--
-- DELETE FROM securityEventNames WHERE name = 'account.signin.confirm.bypass.ip';
--
-- UPDATE dbMetadata SET value = '175' WHERE name = 'schema-patch-level';
