-- SET NAMES utf8mb4 COLLATE utf8mb4_bin;
--
-- DELETE FROM securityEventNames WHERE name = 'account.recovery_phone_replace_complete';
-- DELETE FROM securityEventNames WHERE name = 'account.recovery_phone_replace_failure';
--
-- UPDATE dbMetadata SET value = '169' WHERE name = 'schema-patch-level';
