
CREATE TABLE IF NOT EXISTS accounts (
  uid BINARY(16) PRIMARY KEY,
  normalizedEmail VARCHAR(255) NOT NULL UNIQUE KEY,
  email VARCHAR(255) NOT NULL,
  emailCode BINARY(16) NOT NULL,
  emailVerified BOOLEAN NOT NULL DEFAULT FALSE,
  kA BINARY(32) NOT NULL,
  wrapWrapKb BINARY(32) NOT NULL,
  authSalt BINARY(32) NOT NULL,
  verifyHash BINARY(32) NOT NULL,
  verifierVersion TINYINT UNSIGNED NOT NULL,
  verifierSetAt BIGINT UNSIGNED NOT NULL,
  createdAt BIGINT UNSIGNED NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sessionTokens (
  tokenid BINARY(32) PRIMARY KEY,
  tokendata BINARY(32) NOT NULL,
  uid BINARY(16) NOT NULL,
  createdAt BIGINT UNSIGNED NOT NULL,
  INDEX session_uid (uid)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS keyfetchTokens (
  tokenid BINARY(32) PRIMARY KEY,
  authKey BINARY(32) NOT NULL,
  uid BINARY(16) NOT NULL,
  keyBundle BINARY(96) NOT NULL,
  createdAt BIGINT UNSIGNED NOT NULL,
  INDEX key_uid (uid)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS resetTokens (
  tokenid BINARY(32) PRIMARY KEY,
  tokendata BINARY(32) NOT NULL,
  uid BINARY(16) NOT NULL UNIQUE KEY,
  createdAt BIGINT UNSIGNED NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS passwordForgotTokens (
  tokenid BINARY(32) PRIMARY KEY,
  tokendata BINARY(32) NOT NULL,
  uid BINARY(16) NOT NULL UNIQUE KEY,
  passcode BINARY(16) NOT NULL,
  createdAt BIGINT UNSIGNED NOT NULL,
  tries SMALLINT UNSIGNED NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS passwordChangeTokens (
  tokenid BINARY(32) PRIMARY KEY,
  tokendata BINARY(32) NOT NULL,
  uid BINARY(16) NOT NULL,
  createdAt BIGINT UNSIGNED NOT NULL,
  INDEX session_uid (uid)
) ENGINE=InnoDB;
