---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fxa-graphql-api
  description: Provides customer settings and account management.
  annotations:
    sentry.io/project-slug: mozilla/fxa-graphql-api
    circleci.com/project-slug: github/mozilla/fxa
  tags:
    - typescript
    - node
    - nestjs
    - graphql
spec:
  type: service
  lifecycle: production
  owner: fxa-devs
  system: mozilla-accounts
  consumesApis:
    - api:fxa-auth
