## FlowSetup2faApp

flow-setup-2fa-qr-heading = Connect to your authenticator app
flow-setup-2a-qr-instruction = <strong>Step 1:</strong> Scan this QR code using any authenticator app, like Duo or Google Authenticator.

# Alt text for the QR-code image shown during two-step authentication setup.
# “setup secret key” refers to the long code you can copy instead of scanning.
# Not to be confused with the 6-digit codes generated by the authenticator app.
flow-setup-2a-qr-alt-text =
  .alt = QR code for setting up two-step authentication. Scan it, or choose "Can’t scan QR code?" to get a setup secret key instead.

flow-setup-2fa-cant-scan-qr-button = Can’t scan QR code?

flow-setup-2fa-manual-key-heading = Enter code manually
flow-setup-2fa-manual-key-instruction = <strong>Step 1:</strong> Enter this code in your preferred authenticator app.
flow-setup-2fa-scan-qr-instead-button = Scan QR code instead?

# links to https://support.mozilla.org/kb/secure-firefox-account-two-step-authentication#w_step-one
flow-setup-2fa-more-info-link = Learn more about authenticator apps
flow-setup-2fa-button = Continue

flow-setup-2fa-step-2-instruction = <Strong>Step 2:</strong>Enter the code from your authenticator app.
flow-setup-2fa-input-label = Enter 6-digit code

##
