[hekad]
base_dir = "/home/app/hekad"

[StatsdInput]
address = ":8125"

[StatAccumInput]

[fxa-content-server-log]
type = "LogfileInput"
logfile = "/home/app/var/log/fxa-content-server.js.log"
logger = "fxa-content-server"

[nginx-access-log]
type = "LogfileInput"
logfile = "/home/proxy/var/log/nginx/access.log"
decoder = "nginx-log-decoder"

[nginx-log-decoder]
type = "PayloadRegexDecoder"
timestamp_layout = "02/Jan/2006:15:04:05 -0700"
match_regex = '^(?P<RemoteIP>\S+) \S+ \S+ \[(?P<Timestamp>[^\]]+)\] "(?P<Method>[A-Z\-]+) (?P<Url>[^\s]+)[^"]*" (?P<StatusCode>\d+) (?P<RequestSize>\d+) "(?P<Referer>[^"]*)" "(?P<Browser>[^"]*)"'

[nginx-log-decoder.message_fields]
Type = "logfile"
Logger = "nginx"
App = "fxa-content-server"
Url|uri = "%Url%"
Method = "%Method%"
Status = "%StatusCode%"
RequestSize|B = "%RequestSize%"
Referer = "%Referer%"
Browser = "%Browser%"

[aggregator-output]
type = "AMQPOutput"
message_matcher = "TRUE"
url = "amqp://heka:guest@logs.dev.lcip.org:5672/"
exchange = "heka"
exchangeType = "fanout"
