/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/**
 * This is a special channel that communicates between two
 * tabs of the same browser. It uses one of two adapaters to
 * communicate: BroadcastChannelAdapter or LocalStorageAdapter.
 *
 * The preferred adapter is the BroadcastChannelAdapter. It uses
 * the BroadcastChannel API to communicate between browser tabs. See
 * https://developer.mozilla.org/docs/Web/API/Broadcast_Channel_API.
 * The BroadcastChannelAdapter is the prefered way to communicate
 * because it does not write any sensitive data to disk.
 *
 * LocalStorageAdapter uses localStorage and storage events to communicate
 * between tabs. LocalStorageAdapter is used for legacy browsers without
 * BroadcastChannel API support. Any data sent over this channel
 * can be written to disk, so care must be taken to ensure all
 * sensitive data is erased as soon as it is consumed by the receiving tab.
 */

define([
  'backbone',
  'crosstab',
  'underscore'
], function (Backbone, crosstab, _) {
  'use strict';

  var BROADCAST_CHANNEL_ID = 'firefox_accounts';

  function BroadcastChannelAdapter(options) {
    options = options || {};
    var win = options.window || window;

    this._broadcastChannel = new win.BroadcastChannel(BROADCAST_CHANNEL_ID);
    this._broadcastChannel.onmessage = this.onMessage.bind(this);
  }

  BroadcastChannelAdapter.prototype = {
    onMessage: function (event) {
      var envelope = JSON.parse(event.data);
      this.trigger(envelope.name, {
        // TODO something about this `data` field doesn't seem right, it seems
        // like this is an opportune time to ditch it.
        data: envelope.data
      });
    },

    send: function (name, data) {
      this._broadcastChannel.postMessage(this.stringify(name, data));
    },

    clear: function () {
      // do nothing
    },

    /**
     * stringify a message, exposed for testing
     *
     * @param {string} name
     * @param {object} [data]
     * @returns {string}
     */
    stringify: function (name, data) {
      return JSON.stringify({
        data: data || {},
        name: name
      });
    }
  };

  _.extend(BroadcastChannelAdapter.prototype, Backbone.Events);


  function LocalStorageAdapter(options) {
    this._crosstab = options.crosstab || crosstab;
  }

  LocalStorageAdapter.prototype = {
    send: function (name, data) {
      // Sensitive data is sent across the channel and should only
      // be in localStorage if absolutely necessary. Only send
      // data if another tab is listening.
      try {
        if (this._crosstab.util.tabCount() > 1) {
          this._crosstab.broadcast(name, data, null);
        }
      } catch (e) {
        // this can blow up if the browser does not support localStorage
        // or if on a mobile device. Ignore the error.
      }
    },

    on: function (name, callback) {
      // crosstab registers callbacks by storing functions by a list
      // of keys. If no key is given, a key is generated by converting the
      // function to a string. This means a given function can only be
      // registered once unless a key is also passed in during registration.
      // Use the current date plus a random number in case two functions are
      // reigstered in the same millisecond.
      var key = Date.now() + Math.random();
      this._crosstab.util.events.on(name, callback, key);
      return key;
    },

    off: function (name, key) {
      this._crosstab.util.events.off(name, key);
    },

    clear: function () {
      this._crosstab.util.clearMessages();
    }
  };

  function InterTabChannel(options) {
    options = options || {};
    var win = options.window || window;

    if (options.adapter) {
      this._adapter = options.adapter;
    } else if (_.isFunction(win.BroadcastChannel)) {
      this._adapter = new BroadcastChannelAdapter(options);
    } else {
      this._adapter = new LocalStorageAdapter(options);
    }
  }

  InterTabChannel.prototype = {
    /**
     * Send a message
     *
     * @method send
     * @param {string} name
     * @param {object} [data]
     */
    send: function (name, data) {
      return this._adapter.send(name, data);
    },

    /**
     * Register a listener
     *
     * @method on
     * @param {string} name
     * @param {function} callback
     *
     * @return {string} key - key used to unregister a listener
     */
    on: function (name, callback) {
      return this._adapter.on(name, callback);
    },

    /**
     * Unregister a listener
     *
     * @method off
     * @param {string} name
     * @param {string} key
     */
    off: function (name, callback) {
      return this._adapter.off(name, callback);
    },

    /**
     * Clear all data.
     *
     * @method clear
     */
    clear: function () {
      return this._adapter.clear();
    }
  };

  InterTabChannel.BroadcastChannelAdapter = BroadcastChannelAdapter;
  InterTabChannel.LocalStorageAdapter = LocalStorageAdapter;


  return InterTabChannel;
});
