-- SET NAMES utf8mb4 COLLATE utf8mb4_bin;
--
-- DELETE FROM emailTypes WHERE emailType = 'subscriptionFailedPaymentsCancellation';
--
-- UPDATE dbMetadata SET value = '117' WHERE name = 'schema-patch-level';
