-- -- the codes to unlock an account
-- CREATE TABLE accountUnlockCodes (
--   uid BINARY(16) PRIMARY KEY NOT NULL,
--   unlockCode BINARY(16) NOT NULL
-- ) ENGINE=InnoDB;
--
-- DROP PROCEDURE `resetAccount_7`;
-- DROP PROCEDURE `forgotPasswordVerified_5`;
-- DROP PROCEDURE `deleteAccount_9`;
--
-- -- Schema patch-level decrement.
-- UPDATE dbMetadata SET value = '31' WHERE name = 'schema-patch-level';
