-- DROP PROCEDURE `accountEmails_4`;
-- DROP PROCEDURE `accountDevices_7`;
-- DROP PROCEDURE `accountExists_2`;
-- DROP PROCEDURE `consumeSigninCode_3`;
-- DROP PROCEDURE `createEmail_2`;
-- DROP PROCEDURE `deleteEmail_2`;
-- DROP PROCEDURE `keyFetchTokenWithVerificationStatus_2`;
-- DROP PROCEDURE `passwordChangeToken_3`;
-- DROP PROCEDURE `passwordForgotToken_2`;
-- DROP PROCEDURE `sessionToken_4`;
-- DROP PROCEDURE `sessionTokenWithVerificationStatus_3`;
-- DROP PROCEDURE `sessionWithDevice_5`;

-- UPDATE dbMetadata SET value = '53' WHERE name = 'schema-patch-level';
