CREATE TABLE IF NOT EXISTS recoveryCodes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  uid BINARY(16) NOT NULL,
  codeHash BINARY(32) NOT NULL,
  salt BINARY(32) NOT NULL,
  UNIQUE KEY (uid, codeHash)
) ENGINE=InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_bin
