CREATE TABLE `sessionTokens` (
  `tokenId` binary(32) NOT NULL,
  `tokenData` binary(32) NOT NULL,
  `uid` binary(16) NOT NULL,
  `createdAt` bigint(20) unsigned NOT NULL,
  `uaBrowser` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `uaBrowserVersion` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `uaOS` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `uaOSVersion` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `uaDeviceType` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lastAccessTime` bigint(20) unsigned NOT NULL DEFAULT '0',
  `uaFormFactor` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `authAt` bigint(20) unsigned DEFAULT NULL,
  `verificationMethod` int(11) DEFAULT NULL,
  `verifiedAt` bigint(20) DEFAULT NULL,
  `mustVerify` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`tokenId`),
  KEY `session_uid` (`uid`),
  KEY `sessionTokens_createdAt` (`createdAt`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci
