
on: [workflow_dispatch]

name: demo-git-mirror

jobs:
  git-mirror:
    runs-on: [nscloud-ubuntu-22.04-staging-amd64-2x4-with-cache, nscloud-git-mirror-5gb]
    steps:
      - name: Namespace Checkout
        uses: namespacelabs/checkout@HEAD
        with:
            fetch-depth: 10

  actions-checkout:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
